### ISSUE TITLE
Fail to build on ArchLinux

### ISSUE THREAD

**Issue by teon** [agronick/KyRC#48]
I'm trying to build on ArchLinux and get (msg below). Any idea how to handle this?

```
make[2]: Entering directory '/home/teon/.cache/pacaur/relay-git/src/relay-git/src'
  GEN      ../data/org.agronick.relay.gschema.valid
  VALAC    relay_vala.stamp
warning: -X has no effect when -C or --ccode is set
unity.vapi:97.4-97.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
relay.vala:105.5-108.6: warning: the modifier `static' is not applicable to constants
connection.vala:28.2-28.48: warning: the modifier `static' is not applicable to constants
        public static const uint16 DEFAULT_PORT = 6667;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rich_text.vala:27.5-27.92: warning: the modifier `static' is not applicable to constants
    private static const string url_string = """(http|https?|ftp):\/\/[^\s\/$.?#].[^\s]*""";
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
relay.vala:253.26-253.32: error: The type name `postFix' could not be found
                    return c*(7.5625f*(postFix)*t + 0.75f) + b;
                                       ^^^^^^^
relay.vala:256.26-256.32: error: The type name `postFix' could not be found
                    return c*(7.5625f*(postFix)*t + 0.9375f) + b;
                                       ^^^^^^^
relay.vala:259.26-259.32: error: The type name `postFix' could not be found
                    return c*(7.5625f*(postFix)*t + 0.984375f) + b;
                                       ^^^^^^^
Compilation failed: 3 error(s), 5 warning(s)
make[2]: *** [Makefile:610: relay_vala.stamp] Error 1
make[2]: Leaving directory '/home/teon/.cache/pacaur/relay-git/src/relay-git/src'
make[1]: *** [Makefile:461: all-recursive] Error 1
make[1]: Leaving directory '/home/teon/.cache/pacaur/relay-git/src/relay-git'
```

**Comment by fattredd** [comment]
I am getting the same error trying to build in Elementary OS 5.0 Juno.
